### PR TITLE
add time stamp, sort tweets based on time on the home page, add retwe…

### PR DESCRIPTION
**Pull request by Sherwin6180**
…ets, comments, and timeStamp to tweet schema

file changed:
+ Timeline.js
+ NewTweet.js
+ tweet.controllers.js
+ tweet.models.js

### CODE REVIEW

**Review by Jinwoo-1162 — COMMENTED** [review]
Why did you choose to sort the comments on the frontend instead of the backend? Are there instances where we want to get the tweets from the database in a non-sorted fashion?

**Comment by Sherwin6180** [comment]
> Why did you choose to sort the comments on the frontend instead of the backend? Are there instances where we want to get the tweets from the database in a non-sorted fashion?

Because on the trending page the tweets are sorted based on likes and retweets. And I don't know how to sort the data on the backend tbh.

**Comment by Jinwoo-1162** [comment]
The backend uses the exact same javascript code as the frontend. You can use the same sorting function, or use the built in sort function in mongoose. Either way, if you think it makes more sense to sort on the frontend, then that's fine with me

**Review by Jinwoo-1162 — APPROVED** [review]

**Comment by Sherwin6180** [comment]
> The backend uses the exact same javascript code as the frontend. You can use the same sorting function, or use the built in sort function in mongoose. Either way, if you think it makes more sense to sort on the frontend, then that's fine with me

By backend, do you mean sort them when we fetch data in the Home.js, and then pass the sorted array to Timeline.js?

**Comment by Jinwoo-1162** [comment]
Backend as in server.js. Everything regarding the React app is considered frontend

**Pull request merged**
